<?php
header("Content-type: text/xml; charset=UTF-8");
echo '<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/skin/css/sitemap.xsl"?>';
include './includes/tlca_world.php';
$check = $tlca_do->load('class_check');
$class_index = $tlca_do->load('class_index');
$page = intval($_REQUEST['page']);
$loai = addslashes(strip_tags($_REQUEST['loai']));
$setting = mysqli_query($conn, "SELECT * FROM index_setting ORDER BY name ASC");
while ($r_s = mysqli_fetch_assoc($setting)) {
	$index_setting[$r_s['name']] = $r_s['value'];
}
$limit = 500;
$start = $page * $limit - $limit;
if ($loai == 'phim') {
	$thongtin = mysqli_query($conn, "SELECT * FROM phim ORDER BY id ASC LIMIT $start,$limit");
	while ($r_tt = mysqli_fetch_assoc($thongtin)) {
		$list .= '<url><loc>' . $index_setting['link_domain'] . '/thong-tin-phim/'.$r_tt['link'].'-'.$r_tt['id'].'.html</loc></url>';
	}
	?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<?php
echo $list;
	?>
</urlset>
	<?php

}else if ($loai == 'tap') {
	$thongtin = mysqli_query($conn, "SELECT list_tap.*,phim.link FROM list_tap INNER JOIN phim ON list_tap.phim=phim.id ORDER BY list_tap.phim DESC,list_tap.thu_tu ASC LIMIT $start,$limit");
	while ($r_tt = mysqli_fetch_assoc($thongtin)) {
		$list .= '<url><loc>' . $index_setting['link_domain'] . '/xem-phim/'.$r_tt['link'].'-episode-id-'.$r_tt['id'].'.html</loc></url>';
	}
	?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<?php
echo $list;
	?>
</urlset>
	<?php

}else if ($loai == 'category') {
	$thongtin = mysqli_query($conn, "SELECT * FROM category ORDER BY cat_id ASC");
	while ($r_tt = mysqli_fetch_assoc($thongtin)) {
		$list .= '<url><loc>' . $index_setting['link_domain'] . '/the-loai/'.$r_tt['cat_blank'].'.html</loc></url>';
	}
	?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<?php
echo $list;
	?>
</urlset>
	<?php

} else if ($loai == 'page') {
	$list .= '<url><loc>' . $index_setting['link_domain'] . '</loc></url>';
	$list .= '<url><loc>' . $index_setting['link_domain'] . '/lien-he.html</loc></url>';
	$list .= '<url><loc>' . $index_setting['link_domain'] . '/dieu-khoan.html</loc></url>';
	?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<?php
echo $list;
	?>
</urlset>
	<?php

} else {
	$thongtin_truyen = mysqli_query($conn, "SELECT count(*) AS total FROM phim");
	$r_t = mysqli_fetch_assoc($thongtin_truyen);
	$total_page_truyen = ceil($r_t['total'] / $limit);
	for ($i = 0; $i < $total_page_truyen; $i++) {
		$n = $i + 1;
		$list_truyen .= '<sitemap><loc>' . $index_setting['link_domain'] . '/phim-' . $n . '.xml</loc></sitemap>';
	}
	$thongtin_tap = mysqli_query($conn, "SELECT count(*) AS total FROM list_tap");
	$r_tap = mysqli_fetch_assoc($thongtin_tap);
	$total_page_tap = ceil($r_tap['total'] / $limit);
	for ($i = 0; $i < $total_page_tap; $i++) {
		$n = $i + 1;
		$list_tap .= '<sitemap><loc>' . $index_setting['link_domain'] . '/tap-phim-' . $n . '.xml</loc></sitemap>';
	}
	$list_page = '<sitemap><loc>' . $index_setting['link_domain'] . '/page.xml</loc></sitemap>';
	$list_category = '<sitemap><loc>' . $index_setting['link_domain'] . '/category.xml</loc></sitemap>';
	?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<?php
	//echo $list_page;
	echo $list_category;
	echo $list_truyen;
	echo $list_tap;
	?>
</sitemapindex>
<?php
}
?>
<!-- XML Sitemap generated by code chuẩn -->